### ISSUE TITLE
Versions table is updated even though not run

### ISSUE THREAD

**Issue by andersgs** [tseemann/nullarbor#103]
I just re-ran Nullarbor with on an old report. I just needed a subset of the isolates, and wanted it in the new format. So, essentially, the only thing that was re-run was fasttree, snippy-core, and roary. I noticed that the software versions table has been updated with all the current software versions, even though new assemblies were not run, or MLST, or Abricate, or Kraken.

Hum...

**Comment by tseemann** [comment]
This problem is not really solveable. If you do incremental updates, then each assembly could be a different version of megahit etc.   

It might be possible to attach a version of each tool to a log of output file and version of tool. But some outputs come from multiple files.

Too hard basket I'm afraid.
