### ISSUE TITLE
Feature request: send nullarbor.pl log progress to stderr and the pipeline run command to stdout

### ISSUE THREAD

**Issue by schultzm** [tseemann/nullarbor#127]
There is a recommendation in the nullarbor`README.md` to cut and paste the run command from the `nullarbor.pl` output to actually run the job.

It might be useful instead to output the `nullarbor.pl` progress output to `stderr`, and send the actual run command to `stdout`.  This way, the end user could run the job by piping stdout of `nullarbor.pl` to shell.    For example, `nullarbor.pl --name PROJNAME --mlst saureus --ref US300.fna --input samples.tab --outdir OUTDIR | sh`

Cheers 🍺

**Comment by tseemann** [comment]
@schultzm it is not possible to do what you say, because the command run order is determined dynamically by the `make` jobserver. it can't know in advance what commands will be needed until each dependency is checked. Well, it could be maybe done in the simple case, but it wouldn't be able to run things in parallel like it does now, it would be one step at a time. Sorry.

**Comment by tseemann** [comment]
@schultzm  I think i might have misunderstood. do you mean *just* the `nice make ...` command?

If so, just use the 'secret' `--run` option on your command line :)

**Comment by schultzm** [comment]
Thanks! Is this a new feature?  Will you add this to the `readme` and the `--help`?
