### ISSUE TITLE
Can I start the pipeline at the forth step 'Annotation'

### ISSUE THREAD

**Issue by tigerxu** [tseemann/nullarbor#213]
Hi, 

I have assembled contigs for the collected genomes. I'm wondering if I can start the nullarbor pipeline at the forth step 'Annotation'?

Thank you very much!

Zhuofei

**Comment by tseemann** [comment]
Yes, you can copy the contigs into their `SAMPLEID/contigs.fa` location and the Makefile should just use them instead of assembling them again.

The other way is to edit `nullarbor.conf` and the `[prefill]` section.

Please *copy* the files though, do not move them. As there is chance things will go wrong and they will be overwritten.

**Comment by tigerxu** [comment]
Many thanks for your quick reply!
