### ISSUE TITLE
?missing space from nullarbor.pl line 271 for trimmomatic

### ISSUE THREAD

**Issue by ajmerritt1** [tseemann/nullarbor#241]
Hi Torsten, 
I switched on --trim and added CROP:200 to nullarbor.conf but on execution got error:
```
Exception in thread "main" java.io.FileNotFoundException: 
/dev/null/ILLUMINACLIP:/home/nullarbor/nullarbor/conf/trimmomatic.fa:1:30:11 (No such file or directory)
```
adding an extra space at column 107 of line 271 to produce .../dev/null ".($cfg... resolved it.
new bug? known bug? old bug?

thx
Adam

**Comment by tseemann** [comment]
@ajmerritt1 
I think that bug was fixed long ago. the current conf has the space:
`@reads $id/$R1 /dev/null $id/$R2 /dev/null ".($cfg->{trimmomatic} || '') ]`

What version are you using?
```
% nullarbor.pl --version
nullarbor.pl 2.0.20191013
```
FYI - nullarbor is now fully in `bioconda`. Might be easier way to keep up to date.


PS. the trimming would normally happen on the Illumina instrument. do you have this in your `SampleSheet.csv` ?
```
[Settings]
Adapter,CTGTCTCTTATACACATCT
```
Do you use Basespace or run `bcl2fastq` to generate the FASTQ ?

**Comment by ajmerritt1** [comment]
cool - am running version 2.0.20181010 on base env. was a hybrid-'ish install with github v. plus conda deps. 

and am playing with bioconda 2.0.20191013 in a // env, confirmed the space is there the bioconda v.

I was less concerned about adapter trimming, just wanted to drop the last 100bp of my 2x300 reads and look at impact on quality & assembly. would be using basespace for fastq I'd think.

thx

Adam

**Comment by tseemann** [comment]
Yeah, it's interesting to see how things perform when going from 300bp to 150bp PE.
We found Miseq 250/300 PE is usually wasted due to over-fragementation with Nextera XT, and the reads both totally overlap. It's an expensive way to do 250bp SE reads :-)
