### ISSUE TITLE
Conda installation issues

### ISSUE THREAD

**Issue by emmadoughty** [tseemann/nullarbor#255]
I'm having trouble getting the full nullarbor pipeline to run to completion with various installation issues arising. I've tried a lot of things, this largely summarises it:

conda create -n nullarbor -c bioconda kraken kraken2 centrifuge
conda install -c bioconda -c conda-forge -c defaults -c r nullarbor 
#Added extra channels in desperation
#Kraken etc downloaded and export commands added to bashrc
#Generating the run directory, it complained that quicktree was not installed
conda install -c bioconda quicktree
#When I ran the pipeline, it complained about the prokka and tbl2asn versions
conda update -c bioconda prokka
conda update -c bioconda tbl2asn #Couldn't find update
conda install -c bioconda/label/cf201901 tbl2asn #Updated but then nullarbor wouldn't run to generate a run directory
conda update -c bioconda nullarbor #Nullarbor then ran but complained about prokka and tbl2asn again
#Also had issues with make preview as ref.fa wasn't being generated.

Looking for something 'cleaner', my latest install was with:
conda create -n test_null -c bioconda -c conda-forge -c defaults -c r kraken kraken2 centrifuge quicktree prokka tbl2asn nullarbor

I could generate the run directory, dependency check was happy but I think I've got the same issue with tbl2asn again.
[11:05:32] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.14.5 from https://github.com/tseemann/prokka' -Z \/tmp\/tmp\.dNgTbB12Em\/prokka\.err -i \/tmp\/tmp\.dNgTbB12Em\/prokka\.fsa 2> /dev/null
make: *** [Makefile:130: 14442/contigs.gff] Error 2
make: *** Waiting for unfinished jobs....
[nullarbor.log](https://github.com/tseemann/nullarbor/files/4142489/nullarbor.log)

Any help would be greatly appreciated!

**Comment by rpetit3** [comment]
Hi @emmadoughty!

I think you were affected by the expired tbl2asn issue (See https://github.com/tseemann/prokka/issues/453). This was recently fixed in Bioconda (https://github.com/bioconda/bioconda-recipes/pull/20117).

I think if you try creating the environment again it should work for you. 

Otherwise you can use the `test_null` environment you already created and install `tbl2asn-forever` into it.
```
conda activate test_null
conda install -c conda-forge -c bioconda tbl2asn-forever
```

Cheers,
Robert

**Comment by tseemann** [comment]
@rpetit3 is correct.  prokka is fixed in conda now.   you should not need to add any of those manual conda installs - the nullarbor recipe has them all. it suggests something else is wrong. i think you need to set your channel order correctly:
https://bioconda.github.io/user/install.html#set-up-channels
