### ISSUE TITLE
nullarbor quits without completing

### ISSUE THREAD

**Issue by bforde** [tseemann/nullarbor#45]
nullarbor stops without error before finishing. 

final output is

[15:05:58] Walltime used: 0.62 minutes
[15:05:58] If you use this result please cite the Prokka paper:
[15:05:58] Seemann T (2014) Prokka: rapid prokaryotic genome annotation. Bioinformatics. 30(14):2068-9.
[15:05:58] Type 'prokka --citation' for more details.
[15:05:58] Share and enjoy!
make: Leaving directory 

Roary has not been run and no report has been compiled

**Comment by bforde** [comment]
only error I can find in the output is

[15:47:35] Could not find a .aligned.fa file in NS39-01/NS39-01
make: *** [core.aln] Error 255
make: *** Waiting for unfinished jobs....

**Comment by tseemann** [comment]
Seems rather quick. Did you have > 2 isolates ?

**Comment by ramjet10** [comment]
This happens to me also if I run it on only 3 isolates (which turned out to be different ST types), but it only happened when I used spades instead of MEGAHIT. I imagine it just doesn't align anything so it doesn't make a .aligned.fa file?

**Comment by tseemann** [comment]
@ramjet10 Roary also fails if there are less than 3 isolates for some reason.

I need to come up with a solution for the case of no aligned core SNPs. The makefile system I am using makes this a bit tricky!

**Comment by ramjet10** [comment]
Yeah its always hard to write a pipeline that covers all contingencies. I wrote a bash-script pipeline last year that did similar stuff to nullarbor (but not as pretty as yours as I can't really program or script properly) but I was basically editing it for every project and had to use loads of conditional loops to either include some steps or not as I work with several non-pathogens so many of the steps weren't applicable. 

On thing I was thinking of that might work is if you could allow the use of a library of trusted reference genomes for comparisons when using only a few sequences or for divergent isolates. For example I have a few genomes being sequenced that are environmental isolates, which are likely stenotrophomonas and pseudomonas species. It would be nice if I could put these in the pipeline and get trees, SNP distances and pan genome comparisons with current fully sequenced genomes. Reference genomes could be automatically chosen from the kraken output or user-submitted. This would make the output more useful for de novo identification of unknown isolates and might overcome the issues with alignments from small numbers of sequences in roary and other components. Could that work?

**Comment by ramjet10** [comment]
The same error keeps happening to me now, only with runs with smaller number of sequences, but even runs with 6-8 sequences fail with this "Could not find a .aligned.fa" error.
Its weird because there are .aligned.fa files in every other directory except for the first one. If you just copy a file in there from one of the other directories it runs through fine (obviously this is not a fix!)

**Comment by ramjet10** [comment]
Now here's a curly one, so I run only 3 strains this time, 2 stenotrophomonas and 1 serratia in a single run, with a stenotrophomonas reference genome and this time, it run to completion without error.
So it can't just be due to a small number of isolates or lack of alignment, in this case the Serratia strain wasn't even closely related to the other sequences.

**Comment by tseemann** [comment]
Common problems are:

* need at least 4 isolates to run Nullarbor
* reference genome with no sequence in it (eg. downloaded GBK since 2016)
* non unix line endings (use `dos2unix` or `mac2unix`)
