### ISSUE TITLE
Full annotation from prokka

### ISSUE THREAD

**Issue by aabarug** [tseemann/nullarbor#62]
Hi Torsten,

Nullarbor currently does not produce fully annotated files from prokka, it would be useful to have an option to enable this.

**Comment by ellisrichardj** [comment]
I have been running into this issue too.  I think this is because nullarbor runs prokka with the --fast option.  I have edited the nullarbor perl script to remove it and it now produces fully annotated files.

However, it would be good to be able to give prokka other options (such as genus and species) from the nullarbor command...

**Comment by tseemann** [comment]
The `--fast` does do annotation but just the basics with `sprot` database (in git HEAD version).

I am still trying to figure out the best way to configure all these things. I think I will end up having options in the `nullarbor.conf` file that you can override with the `--conf` option.

Are there any other settings you are interested in?

**Comment by tseemann** [comment]
@aabarug @ellisrichardj 

This can now be done by the `--fullanno` option.
